version: "3.8"

services:
  master:
    build:
      context: ..
      target: master
    environment:
      REPLICAS: ${REPLICAS:-3}
      VOLUMES: ${VOLUMES:-''}
    volumes:
      - master_data:/app/indexdb/
    ports:
      - "3000:3000"
    networks:
      tinykv_net:

  volume:
    build:
      context: ..
      target: volume
    volumes:
      - volume_data:/app/
    ports:
      - "80"
    networks:
      tinykv_net:

volumes:
  master_data:
    name: "tinykv-master"
  volume_data:
    name: "tinykv-volume"

networks:
  tinykv_net:
    name: "tinykv-network"
