name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run tests
        run: make test

  build:
    name: Build binary
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - darwin
          - linux
          - windows
        goarch:
          - amd64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build
